name: Check Required Files

on:
  push:
    tags:
      - '*'

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for required files and folders
        run: |
          for path in src config resources routes database lang public; do
            if [ ! -e "$path" ]; then
              echo "Missing required path: $path"
              exit 1
            fi
          done
          if [ ! -f src/MpesaPremiumServiceProvider.php ]; then
            echo "Missing src/MpesaPremiumServiceProvider.php"
            exit 1
          fi
